/**
 * A tiny FIFO buffer for outbound frames that are produced while the socket
 * is not open.
 *
 * User input (keystrokes, composed messages, key bytes) is generated by the
 * person, not the protocol — it cannot be regenerated on reconnect the way a
 * SUBSCRIBE or PING can. When the socket is mid-reconnect we hold that input
 * here and flush it in order the moment the pipe reopens, so nothing the user
 * typed is silently lost. The buffer is bounded: once full it drops the oldest
 * frame so a long outage can't grow memory without limit.
 */
export class OutboundQueue<T> {
  private items: T[] = [];
  private readonly max: number;

  constructor(max = 256) {
    this.max = max;
  }

  get size(): number {
    return this.items.length;
  }

  /** Buffer a frame. Oldest is dropped first once the cap is reached. */
  enqueue(item: T): void {
    this.items.push(item);
    if (this.items.length > this.max) this.items.shift();
  }

  /** Send every buffered frame in FIFO order, then empty the buffer. The
   *  buffer is drained before `send` runs so a re-entrant enqueue during
   *  flush lands after this batch rather than being replayed twice. */
  flush(send: (item: T) => void): void {
    if (this.items.length === 0) return;
    const pending = this.items;
    this.items = [];
    for (const item of pending) send(item);
  }

  clear(): void {
    this.items = [];
  }
}
